In [1]:
from google.colab import files
uploaded = files.upload()

Saving housing-price.csv to housing-price.csv

In [3]:
import pandas as pd

df = pd.read_csv('housing-price.csv')  # change name if needed
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [5]:
#Check missing values
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [6]:
#Convert YES / NO columns to numbers
yes_no_cols = [
    'mainroad', 'guestroom', 'basement',
    'hotwaterheating', 'airconditioning', 'prefarea'
]

df[yes_no_cols] = df[yes_no_cols].replace({'yes': 1, 'no': 0})
df.head()

/tmp/ipython-input-4208898734.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[yes_no_cols] = df[yes_no_cols].replace({'yes': 1, 'no': 0})

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished

In [7]:
#Encode furnishingstatus
df = pd.get_dummies(df, columns=['furnishingstatus'], drop_first=True)
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,False,False
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,False,False
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,True,False
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,False,False
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,False,False

In [8]:
#Separate Features (X) and Target (y)
X = df.drop('price', axis=1)
y = df['price']

In [9]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [11]:
#Train/Test separate
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [10]:
#Linear Regression (House Price Prediction)

In [21]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

#R² Score
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
r2

#RMSE (Error in Price Units)
import numpy as np
from sklearn.metrics import mean_squared_error

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
rmse
print(f"RMSE: {rmse}")
print(f"R Square Score: {r2}")

coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': lr.coef_
})

coefficients.sort_values(by='Coefficient', ascending=False)

RMSE: 1324506.9600914405
R Square Score: 0.6529242642153175

                            Feature    Coefficient
2                         bathrooms  549420.501241
0                              area  511615.563777
8                   airconditioning  367817.894916
3                           stories  353158.429856
10                         prefarea  267018.660812
9                           parking  193542.781675
6                          basement  186194.150506
7                   hotwaterheating  143233.206250
4                          mainroad  128151.921295
5                         guestroom   88590.213462
1                          bedrooms   56615.572458
11  furnishingstatus_semi-furnished  -62550.297211
12     furnishingstatus_unfurnished -193987.781088

In [28]:
#KNN REGRESSION

In [27]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

# R² Score
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)

# RMSE
import numpy as np
from sklearn.metrics import mean_squared_error

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"RMSE: {rmse}")
print(f"R Square Score: {r2}")

RMSE: 1397361.9354594736
R Square Score: 0.6136921076371805

In [29]:
#POLYNOMIAL REGRESSION

In [24]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X_scaled)

from sklearn.model_selection import train_test_split
X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(
    X_poly, y, test_size=0.2, random_state=42
)

poly_lr = LinearRegression()
poly_lr.fit(X_train_p, y_train_p)

y_pred = poly_lr.predict(X_test_p)

# R² Score
from sklearn.metrics import r2_score
r2 = r2_score(y_test_p, y_pred)

# RMSE
import numpy as np
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test_p, y_pred))

print(f"RMSE: {rmse}")
print(f"R Square Score: {r2}")

RMSE: 1379003.8035725856
R Square Score: 0.623775831063538

In [30]:
#DECISION TREE REGRESSION

In [31]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)

y_pred = dt.predict(X_test)

# R² Score
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)

# RMSE
import numpy as np
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"RMSE: {rmse}")
print(f"R Square Score: {r2}")

RMSE: 1625669.904259373
R Square Score: 0.4771459275854347